### ISSUE TITLE
About the mask strategy

### ISSUE THREAD

**Issue by zhangfang97** [chaytonmin/Voxel-MAE#21]
Hi, I have run your code in kitti. During debugging,   id_list_select_30  and  id_list_select_30to50  are always empty, which means that  almost all the voxels are in  id_list_select_50. This seems strange. Did I make a mistake? 
Thanks for you help.

**Comment by nuoloveheng** [comment]
I think this is a bug in this repo. You need use voxel_coords_distance = ((voxel_coords[:,2]* voxel_size[0])**2  + (voxel_coords[:,3]*voxel_size[1])**2)**0.5 instead of voxel_coords_distance = (voxel_coords[:,2]**2 + voxel_coords[:,3]**2)**0.5.

**Comment by zhangfang97** [comment]
Great, I undertand it. I truly appreciate your timely help.
