### ISSUE TITLE
KeyError: 'road_plane'

### ISSUE THREAD

**Issue by FrontierBreaker** [chaytonmin/Voxel-MAE#26]
Is road_plane used during the pretraining for KITTI? 

  File "../pcdet/datasets/kitti/kitti_dataset.py", line 427, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "../pcdet/datasets/dataset.py", line 130, in prepare_data
    'gt_boxes_mask': gt_boxes_mask
  File "../pcdet/datasets/augmentor/data_augmentor.py", line 240, in forward
    data_dict = cur_augmentor(data_dict=data_dict)
  File "../pcdet/datasets/augmentor/database_sampler.py", line 252, in __call__
    data_dict = self.add_sampled_boxes_to_scene(data_dict, sampled_gt_boxes, total_valid_sampled_dict)
  File "../pcdet/datasets/augmentor/database_sampler.py", line 168, in add_sampled_boxes_to_scene
    sampled_gt_boxes, data_dict['road_plane'], data_dict['calib']
KeyError: 'road_plane'

**Comment by chaytonmin** [comment]
> Is road_plane used during the pretraining for KITTI?
> 
> File "../pcdet/datasets/kitti/kitti_dataset.py", line 427, in **getitem** data_dict = self.prepare_data(data_dict=input_dict) File "../pcdet/datasets/dataset.py", line 130, in prepare_data 'gt_boxes_mask': gt_boxes_mask File "../pcdet/datasets/augmentor/data_augmentor.py", line 240, in forward data_dict = cur_augmentor(data_dict=data_dict) File "../pcdet/datasets/augmentor/database_sampler.py", line 252, in **call** data_dict = self.add_sampled_boxes_to_scene(data_dict, sampled_gt_boxes, total_valid_sampled_dict) File "../pcdet/datasets/augmentor/database_sampler.py", line 168, in add_sampled_boxes_to_scene sampled_gt_boxes, data_dict['road_plane'], data_dict['calib'] KeyError: 'road_plane'

No.  Our voxel-MAE is self-supervised. No labels of gt boxes are used in training.
You can refer to this error in OpenPCDet.

**Comment by FrontierBreaker** [comment]
I met this error when I run your code of voxel-mae pretraining on kitti. So you mean the road_plane is redundant to load in the code?

**Comment by chaytonmin** [comment]
> I met this error when I run your code of voxel-mae pretraining on kitti. So you mean the road_plane is redundant to load in the code?

yes. We just keep the codes for simplicity.

**Comment by FrontierBreaker** [comment]
Got it. Thank you all the way!!
