### ISSUE TITLE
Question about UDA(ST3D)

### ISSUE THREAD

**Issue by Yontara** [chaytonmin/Voxel-MAE#8]
Hi! Thank you for your research on the good idea.
I would like to ask you a question about UDA.
In your paper, you mentioned that you used the pre-trained model by Voxel-MAE to train ST3D.
But I'm wondering how did you adapted your model to ST3D.
Did you apply the model to ST3D after going through the downstream process?
And I didn't even understand how you trained the model on both source and target data to train ST3D.
Again, thank you for sharing your great work and your codes.
I'll be waiting for the reply. Thanks

**Comment by Yontara** [comment]
![image](https://user-images.githubusercontent.com/112155383/186840226-e0ab01cd-efb4-4c8a-94b6-113b69f7db78.png)

**Comment by chaytonmin** [comment]
> Hi! Thank you for your research on the good idea. I would like to ask you a question about UDA. In your paper, you mentioned that you used the pre-trained model by Voxel-MAE to train ST3D. But I'm wondering how did you adapted your model to ST3D. Did you apply the model to ST3D after going through the downstream process? And I didn't even understand how you trained the model on both source and target data to train ST3D. Again, thank you for sharing your great work and your codes. I'll be waiting for the reply. Thanks

We adopt our Voxel-MAE to ST3D like this:
![图片2](https://user-images.githubusercontent.com/40260488/187565584-47c72c3b-090f-4466-858e-03850e9a4bfd.png)

**Comment by chaytonmin** [comment]
> Hi! Thank you for your research on the good idea. I would like to ask you a question about UDA. In your paper, you mentioned that you used the pre-trained model by Voxel-MAE to train ST3D. But I'm wondering how did you adapted your model to ST3D. Did you apply the model to ST3D after going through the downstream process? And I didn't even understand how you trained the model on both source and target data to train ST3D. Again, thank you for sharing your great work and your codes. I'll be waiting for the reply. Thanks

We adopt our Voxel-MAE to ST3D like this:
![图片3](https://user-images.githubusercontent.com/40260488/187565809-531b19e6-8af2-4f08-a23d-3761a939e342.png)
