### ISSUE TITLE
Reconstruction performance on KITTI 

### ISSUE THREAD

**Issue by ZENGXH** [chaytonmin/Voxel-MAE#9]
Hi @chaytonmin, thanks for releasing the code! 

I am trying to train the Voxel-MAE model on KITTI dataset, and try to visualize the reconstruction results. Here is a example I got at epoch30: 
![image](https://user-images.githubusercontent.com/12856437/188000089-f3a6528a-6518-4c65-a73c-efe1b77391f0.png)
From top to bottom, it shows the ground truth, the masked input and the model output. It seems that the model didn't reconstruct the input well. I am wondering if this is expected or not? If not, do you have idea which part could be wrong? 

Moreover, may I ask which dataset are you using in Figure 3.

**Comment by chaytonmin** [comment]
> Hi @chaytonmin, thanks for releasing the code!
> 
> I am trying to train the Voxel-MAE model on KITTI dataset, and try to visualize the reconstruction results. Here is a example I got at epoch30: ![image](https://user-images.githubusercontent.com/12856437/188000089-f3a6528a-6518-4c65-a73c-efe1b77391f0.png) From top to bottom, it shows the ground truth, the masked input and the model output. It seems that the model didn't reconstruct the input well. I am wondering if this is expected or not? If not, do you have idea which part could be wrong?
> 
> Moreover, may I ask which dataset are you using in Figure 3.

We use KITTI in Figure 3.

How do you visualize the reconstruction results?  What is the masking ratio?

**Comment by ZENGXH** [comment]
Thanks for your reply! I found the issue: it's because I only plot the top-5000 points in the reconstruction image. If I increase the number it looks better.

**Comment by huixiancheng** [comment]
Hi, xiaohui. @ZENGXH  Would you like to share your vis code ? If it still exists. :joy_cat: I'm confused about getting points from dense's features.
